### ISSUE TITLE
Differential gene analysis

### ISSUE THREAD

**Issue by aluisascosta** [datascience-mobi-2023/topic05_team03#6]
@RobertSchwarz1  and @eranlevi02 in connection with the differential gene analysis on your dataset you need to consider:
- normality of the data (checked before any test is performed);
- the need for correction of the resulting p-values. 

On point 2, you can use the function `p.adjust()` if there is a large amount of testing being done. 
Link with references:
https://stat.ethz.ch/R-manual/R-devel/library/stats/html/p.adjust.html

**Comment by RobertSchwarz1** [comment]
Hi Ana,we are looking forward to our meeting later today. I am texting you to make sure that the time of our meeting later is 12:15 o'clock. Is this correct? Kind regards and until then,RobertSent from my Galaxy
-------- Original message --------From: "Ana Luisa S. Costa" ***@***.***> Date: 22/06/2023  12:56  (GMT+01:00) To: datascience-mobi-2023/topic05_team03 ***@***.***> Cc: RobertSchwarz1 ***@***.***>, Mention ***@***.***> Subject: [datascience-mobi-2023/topic05_team03] Differential gene analysis (Issue #6) 
@RobertSchwarz1  and @eranlevi02 in connection with the differential gene analysis on your dataset you need to consider:

normality of the data (checked before any test is performed);
the need for correction of the resulting p-values.

On point 2, you can use the function p.adjust() if there is a large amount of testing being done.
Link with references:
https://stat.ethz.ch/R-manual/R-devel/library/stats/html/p.adjust.html

**Comment by aluisascosta** [comment]
Hi @RobertSchwarz1 , I think our meeting is at 12h10 but 12h15 is also fine by me.

**Comment by RobertSchwarz1** [comment]
Hi Ana,

I have uploaded a file "Robert Problems_Solutions" where I explain a bit the problems I encountered with the differential gene expression analysis for liver cancer. The problem occurred after I checked for normality of the data, as previously discussed. Could you please take a look when you have some time? Thank you very much!
Kind regards,
Robert

Am Mittwoch, Juli 05, 2023 15:49 CEST, schrieb "Ana Luisa S. Costa" ***@***.***>:
 
 
Closed #6 as completed.

**Comment by aluisascosta** [comment]
Hi Robert,

First of all, what is this I see in line 70? You need to verify normality (as you did with Shapiro-Wilk test later in the markdown) before applying **any** other test, as only after checking normality you can decide on which test to perform! Remember that most of your data seems to be not normally distributed... 
One more thing: maybe you should sample 17 cell lines from the not-liver set before making the test too, to avoid comparing 400-something cell lines with 17. 

Good job correcting your tests on line 85 :) 

The Shapiro-Wilk test is only done to verify data normality so that you know whether you can apply a t-test or a non-parametric test. You do not need to combine both tests to get your final set of significant genes, as the significance of your set of genes is not dependent on the Shapiro-Wilk test result. The distributions can be not normal but still significantly different.

**Comment by RobertSchwarz1** [comment]
Hey Ana,

thank you for your reply. I have dealt with the issue by performing multiple Wilcoxon Rank Sum Tests. 
My intention with the previous  code was to perform t test to see where I could find any difference in the expression. I performed the Shapiro normality tests afterwards to see which ones of the tests I could trust. Then, I had taken a look at which ones of these gene expression differences are both significant (t-test pass) and come from normally distributed gene expression vectors (Shapiro test pass). Only then I could state that these genes were indeed differentially expressed. The problem was that I was left with the sad number of three genes:))) But this problem is solved now because I have performed the other kind of parametrical test, Wilcoxon Sum Test, where I successfully extracted a couple dozens of genes, amongst which we also find the three from the previous analysis. Thanks for your time and see you soon!

**Comment by RobertSchwarz1** [comment]
Am Donnerstag, Juni 22, 2023 12:56 CEST, schrieb "Ana Luisa S. Costa" ***@***.***>:
 
 
@RobertSchwarz1 and @eranlevi02 in connection with the differential gene analysis on your dataset you need to consider:
 * normality of the data (checked before any test is performed); * the need for correction of the resulting p-values.
On point 2, you can use the function p.adjust() if there is a large amount of testing being done.
Link with references:
https://stat.ethz.ch/R-manual/R-devel/library/stats/html/p.adjust.html
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/datascience-mobi-2023/topic05_team03/issues/6", "url": "https://github.com/datascience-mobi-2023/topic05_team03/issues/6", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]***>Hi Ana,

we are happy to meet you tomorrow. We just wanted to make sure that we are still meeting tomorrow earlier, at 9 o'clock. Is this correct?
Thanks a lot again and kind regards,

Robert on behalf of team 5.3
​​​
